# Generated by Django 3.2.6 on 2021-08-26 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinder', '0008_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='bookfinder.Genre'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
