# Generated by Django 3.2.6 on 2021-08-27 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinder', '0009_auto_20210826_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
